# Generated by Django 5.2.7 on 2025-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BSDRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(verbose_name='Item')),
                ('institucion', models.CharField(max_length=500, verbose_name='Institución')),
                ('proyecto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proyecto')),
                ('cant_articulos_dotados', models.IntegerField(default=0, verbose_name='Cant. Artículos Dotados')),
                ('cant_articulos_faltantes', models.IntegerField(default=0, verbose_name='Cant. Artículos Faltantes')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Total')),
                ('monto_total_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Total Cobrado')),
                ('monto_total_pendiente', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Total Pendiente')),
                ('vertice', models.CharField(choices=[('V1', 'V1'), ('V3', 'V3'), ('V4', 'V4')], max_length=10, verbose_name='Vértice')),
                ('v1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='V1')),
                ('v3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='V3')),
                ('v4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='V4')),
                ('ejecutada', models.CharField(choices=[('EJECUTADA', 'Ejecutada'), ('EN EJECUCION', 'En Ejecución'), ('POR DOTAR', 'Por Dotar')], max_length=20, verbose_name='Estado de Ejecución')),
                ('centros_salud', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Centros de Salud (V3)')),
                ('educacion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Educación')),
                ('deporte_recreacion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Deporte, Recreación, Esparcimiento y Otros')),
                ('unidades_militares', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Unidades Militares')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro BSD',
                'verbose_name_plural': 'Registros BSD',
                'ordering': ['item'],
            },
        ),
    ]
